import React from 'react';
import { useNavigate } from 'react-router-dom';
import './Impact.css';
import AOS from 'aos';
import 'aos/dist/aos.css';
import image from './assets/earth.png';
import image1 from './assets/carbon.png';
import image2 from './assets/sprout.png';
import image3 from './assets/car.png';
import image4 from './assets/mp.png';
import b1 from './assets/b1.jpg';
import b2 from './assets/b2.webp';
import head from './assets/head.png';
import Project from './projects';
import Offset from './Offset';

const Impact=() => {
   const navigate = useNavigate();

   const handleButtonClick = () => {
     navigate('/credits'); // Navigate to the Credit component
   };
  return (
    // header
    <div className="all" background>
      <h1 data-aos="zoom-y-out" data-aos-delay="50">
        Sample heading
      </h1>
      <div className="header">
        <h1 style={{ justifyContent: 'center', textAlign: 'baseline' }}>
          Hey, Eco-Warrior{' '}
          <img
            src={head}
            alt="eco"
            style={{ height: '9vh', opacity: '0.7', marginTop: '1px' }}
          />
        </h1>

        <p className="head2">
          Welcome back. On this Dashboard you can track the progress of your
          chosen impact.
        </p>
        <div style={{ justifyContent: 'flex-end' }}>
          <button className="view-credits-btn" onClick={handleButtonClick}>
            View Carbon Credits
          </button>
        </div>
      </div>

      {/* impact and blogs */}
      {/* <div
        className="card-container"
        style={{ display: 'flex', padding: '0px' }}
      > */}
      <div
        className="card-container"
        style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: '1px' }}
      >
        <div className="card ">
          {/* impact section */}

          <h2>Your Impact</h2>
          <p> This is the impact generated by your company so far!</p>
          <div class="impact-grid">
            <div
              class="impact-subcard "
              style={{
                backgroundColor: '#bab9ba',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
              }}
            >
              {/* <div data-aos="fade-up"> */}
              <div>
                <img
                  src={image}
                  alt="earth"
                  // style={{ height: '100%', width: '50%' }}
                />
                {/* </div> */}
              </div>
              <div style={{ textAlign: 'center' }}>
                <h2>
                  8 months <p>earth positive</p>
                </h2>
              </div>
            </div>
            <div
              className="impact-subcard"
              style={{ backgroundColor: '#bae5ae' }}
            >
              <img src={image1} alt="carbon" />
              <h2>
                3,742<p>tonnes of Co2 offset </p>
              </h2>
            </div>
            <div
              className="impact-subcard"
              style={{ backgroundColor: '#f2f696' }}
            >
              <img src={image2} alt="sprout" />
              <h2>
                467<p>Trees Planted</p>
              </h2>
            </div>
            <div className="impact-subcard">
              <img src={image3} alt="car" />
              <h2>
                29<p>renewable sources installed</p>
              </h2>
            </div>
          </div>
        </div>

        {/* blogs section */}
        <div className="card impact-card">
          <h2>Blogs</h2>
          <p>Dive deeper into potential pathways for carbon offset.</p>

          <div className="blog-grid">
            <div className="blog-subcard">
              <img src={b1} alt="blog 1" className="blog-image" />
              <div className="content">
                <h3>Strategies to reduce emissions from coal supply</h3>
                <p>
                  One of the most effective ways to cut down on coal mine
                  methane is likely to be to cut coal consumption itself.
                  Nonetheless...
                </p>
                <a href="https://coal.gov.in/en/sustainable-development-cell/promoting-renewable">
                  Read more
                </a>
              </div>
            </div>

            <div className="blog-subcard">
              <img src={b2} alt="blog 2" className="blog-image" />
              <div className="content">
                <h3>How Do Carbon Offsetting Projects Work?</h3>
                <p>
                  All companies will have to take responsibility for their
                  carbon footprint and carbon offsetting projects are becoming
                  their strong ally...
                </p>
                <a href="https://carboncredits.com/how-do-carbon-offsetting-projects-work/">
                  Read more
                </a>
              </div>
            </div>
          </div>

          <div className="view-more-container">
            <a href="https://net0.com/blog/carbon-offset">Explore more blogs</a>
          </div>
        </div>
      </div>

      {/* projects */}
      <div>
        <Project />
      </div>

      {/* map */}
      {/* <div data-aos="zoom-in"> */}
      <div
        style={{
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <img src={image4} alt="map" style={{ height: '80vh' }} />
      </div>
      {/* </div> */}

      {/* co2 offset */}

      <div>
        <Offset />
      </div>
    </div>
  );
}

export default Impact;
